// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDNi8WpPQGbfcFWjVn4pLJL47uKzgMOw',
    appId: '1:203285890494:web:0451f6fe15ff46a0d065ef',
    messagingSenderId: '203285890494',
    projectId: 'scale-app-eb89d',
    authDomain: 'scale-app-eb89d.firebaseapp.com',
    storageBucket: 'scale-app-eb89d.firebasestorage.app',
    measurementId: 'G-Z38C0R5X3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakNYYNO1JkHDvj1e4Bh8EfOsTG9dFELI',
    appId: '1:203285890494:android:3deb31715ca65890d065ef',
    messagingSenderId: '203285890494',
    projectId: 'scale-app-eb89d',
    storageBucket: 'scale-app-eb89d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVTfrxWrJ0ngU2-IzOZDOk_FjeMaPwXq4',
    appId: '1:203285890494:ios:1ac42ca2d7efe937d065ef',
    messagingSenderId: '203285890494',
    projectId: 'scale-app-eb89d',
    storageBucket: 'scale-app-eb89d.firebasestorage.app',
    iosBundleId: 'com.example.scaleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVTfrxWrJ0ngU2-IzOZDOk_FjeMaPwXq4',
    appId: '1:203285890494:ios:1ac42ca2d7efe937d065ef',
    messagingSenderId: '203285890494',
    projectId: 'scale-app-eb89d',
    storageBucket: 'scale-app-eb89d.firebasestorage.app',
    iosBundleId: 'com.example.scaleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhDNi8WpPQGbfcFWjVn4pLJL47uKzgMOw',
    appId: '1:203285890494:web:39ba536549c50512d065ef',
    messagingSenderId: '203285890494',
    projectId: 'scale-app-eb89d',
    authDomain: 'scale-app-eb89d.firebaseapp.com',
    storageBucket: 'scale-app-eb89d.firebasestorage.app',
    measurementId: 'G-Y84HEDGMMD',
  );
}
